export const SET_COMPANY_CODE = "SET_COMPANY_CODE";
export const FETCH_TIME_SERIES_REQUEST = "FETCH_TIME_SERIES_REQUEST";
export const FETCH_TIME_SERIES_SUCCESS = "FETCH_TIME_SERIES_SUCCESS";
export const FETCH_TIME_SERIES_ERROR = "FETCH_TIME_SERIES_ERROR";
export const FETCH_COMPANIES_REQUEST = "FETCH_COMPANIES_REQUEST";
export const FETCH_COMPANIES_SUCCESS = "FETCH_COMPANIES_SUCCESS";
export const FETCH_COMPANIES_ERROR = "FETCH_COMPANIES_ERROR";